server:
  port: 8070
  context-path: /student

logging:
  level:
    root: INFO
    com.tss: DEBUG

user:
  student:
    infoUrl: http://localhost:8070/student/account/getUserBaseInfoBySessionId/
    
spring:
  application:
    name: tss-student

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8090/eureka-server/eureka/
#  instance:
#    metadata-map: 
#      management:
#        context-path: ${server.context-path}/actuator
#    health-check-url: http://localhost:${server.port}${server.context-path}/actuator/health
#    status-page-url: http://localhost:${server.port}${server.context-path}/swagger-ui.html
#    status-page-url: http://localhost:${server.port}${server.context-path}/actuator/info
#    home-page-url: http://localhost:${server.port}/

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 30000
hystrix: 
  command: 
    default: 
      execution: 
        isolation: 
          thread: 
            timeoutInMilliseconds: 30000

account:
  serviceId: TSS-ACCOUNT
report:
  serviceId: TSS-REPORT