server:
  port: 8070
#  context-path: /student

spring:
  application:
    name: student
  zipkin:
      base-url: http://dev.tss.com:8010
  sleuth:
      sampler:
        # 100%的概率将链路的数据上传给Zipkin Server，默认0.1
        percentage: 1.0

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://dev.tss.com:8090/eureka/
#  instance:
#    metadata-map: 
#      management:
#        context-path: ${server.context-path}/actuator
#    health-check-url: http://dev.tss.com:${server.port}${server.context-path}/actuator/health
#    status-page-url: http://dev.tss.com:${server.port}${server.context-path}/swagger-ui.html
#    status-page-url: http://dev.tss.com:${server.port}${server.context-path}/actuator/info
#    home-page-url: http://dev.tss.com:${server.port}/

logging:
  level:
    root: INFO
    com.tss: DEBUG

account:
  contextPath: /account 
  serviceId: account
report:
  serviceId: TSS-REPORT
